#!/usr/bin/env python3
"""Regenerate VLM metadata for selected catalog assets and compare outputs.

This is intentionally separate from index_assets.py:
- no Postgres/Qdrant/Docker dependency
- no UE dependency when existing render views are present
- does not overwrite the production catalog

It reuses each asset's stored render images and measured geometry, calls the same
schema-constrained Codex VLM path, writes regenerated JSON records to a separate
output directory, and compares every field generated by the VLM.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any


VLM_FIELD_PATHS = [
    "identity.name",
    "identity.category",
    "identity.subcategory",
    "semantic.short_description",
    "semantic.description",
    "semantic.tags",
    "semantic.style",
    "semantic.materials",
    "semantic.color_palette",
    "semantic.mood",
    "semantic.typical_placement",
    "semantic.function",
    "semantic.affordances",
    "semantic.scene_types",
    "semantic.condition",
    "semantic.setting",
    "geometry.is_symmetric",
]


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)
        f.write("\n")


def parse_asset_ids(raw: str | None, file_path: str | None) -> list[str]:
    ids: list[str] = []
    if raw:
        ids.extend(x.strip() for x in raw.replace("\n", ",").split(",") if x.strip())
    if file_path:
        text = Path(file_path).read_text(encoding="utf-8").strip()
        if text.startswith("{") or text.startswith("["):
            data = json.loads(text)
            if isinstance(data, dict) and isinstance(data.get("asset_ids"), list):
                ids.extend(str(x) for x in data["asset_ids"])
            elif isinstance(data, dict) and isinstance(data.get("assets"), list):
                ids.extend(str(x["asset_id"]) for x in data["assets"] if x.get("asset_id"))
            elif isinstance(data, list):
                for item in data:
                    if isinstance(item, str):
                        ids.append(item)
                    elif isinstance(item, dict) and item.get("asset_id"):
                        ids.append(str(item["asset_id"]))
        else:
            for line in text.splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                ids.append(line.split()[0].strip(","))
    seen = set()
    out = []
    for asset_id in ids:
        if asset_id not in seen:
            out.append(asset_id)
            seen.add(asset_id)
    return out


def find_catalog_records(asset_db_dir: Path) -> dict[str, Path]:
    records: dict[str, Path] = {}
    for path in asset_db_dir.glob("catalog/*/*.json"):
        records[path.stem] = path
    return records


def select_from_manifest(manifest_path: Path, limit: int) -> list[str]:
    manifest = load_json(manifest_path)
    assets = manifest.get("assets", [])
    return [a["asset_id"] for a in assets[:limit] if a.get("asset_id")]


def select_balanced(records: dict[str, Path], limit: int) -> list[str]:
    by_category: dict[str, list[str]] = {}
    for asset_id, path in records.items():
        try:
            rec = load_json(path)
            cat = rec.get("identity", {}).get("category") or path.parent.name
        except Exception:
            cat = path.parent.name
        by_category.setdefault(cat, []).append(asset_id)
    for ids in by_category.values():
        ids.sort()

    selected: list[str] = []
    while len(selected) < limit:
        added = False
        for cat in sorted(by_category):
            ids = by_category[cat]
            if ids:
                selected.append(ids.pop(0))
                added = True
                if len(selected) >= limit:
                    break
        if not added:
            break
    return selected


def get_path(obj: dict[str, Any], dotted: str) -> Any:
    cur: Any = obj
    for part in dotted.split("."):
        if not isinstance(cur, dict):
            return None
        cur = cur.get(part)
    return cur


def normalize_scalar(value: Any) -> Any:
    if isinstance(value, str):
        return " ".join(value.lower().split())
    return value


def normalize_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [" ".join(str(x).lower().split()) for x in value if str(x).strip()]


def compare_values(old: Any, new: Any) -> dict[str, Any]:
    if isinstance(old, list) or isinstance(new, list):
        old_list = normalize_list(old)
        new_list = normalize_list(new)
        old_set = set(old_list)
        new_set = set(new_list)
        union = old_set | new_set
        overlap = old_set & new_set
        return {
            "changed": old_list != new_list,
            "old_count": len(old_list),
            "new_count": len(new_list),
            "overlap_count": len(overlap),
            "jaccard": round(len(overlap) / len(union), 3) if union else 1.0,
            "added": sorted(new_set - old_set),
            "removed": sorted(old_set - new_set),
        }
    return {
        "changed": normalize_scalar(old) != normalize_scalar(new),
        "old": old,
        "new": new,
    }


def compare_records(old: dict[str, Any], new: dict[str, Any]) -> dict[str, Any]:
    fields: dict[str, Any] = {}
    changed = []
    for path in VLM_FIELD_PATHS:
        diff = compare_values(get_path(old, path), get_path(new, path))
        fields[path] = diff
        if diff["changed"]:
            changed.append(path)
    return {
        "asset_id": old.get("identity", {}).get("asset_id"),
        "baseline_name": old.get("identity", {}).get("name"),
        "new_name": new.get("identity", {}).get("name"),
        "baseline_snapshot": output_snapshot(old),
        "new_snapshot": output_snapshot(new),
        "changed_field_count": len(changed),
        "changed_fields": changed,
        "fields": fields,
    }


def output_snapshot(rec: dict[str, Any]) -> dict[str, Any]:
    ident = rec.get("identity", {})
    sem = rec.get("semantic", {})
    tags = sem.get("tags") or []
    materials = sem.get("materials") or []
    return {
        "name": ident.get("name"),
        "category": ident.get("category"),
        "setting": sem.get("setting"),
        "short_description": sem.get("short_description"),
        "tags": tags[:10],
        "materials": materials[:8],
    }


def field_changed(comp: dict[str, Any], field: str) -> bool:
    return bool(comp["fields"][field]["changed"])


def list_jaccard(comp: dict[str, Any], field: str) -> float:
    value = comp["fields"][field].get("jaccard")
    return float(value) if value is not None else 1.0


def safe_model_name(model: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", model).strip("_")


def safe_variant_name(model: str, reasoning_effort: str) -> str:
    base = safe_model_name(model)
    if reasoning_effort == "default":
        return base
    return f"{base}__reasoning-{safe_model_name(reasoning_effort)}"


def parse_models(model: str, models: str | None) -> list[str]:
    raw = models or model
    out = []
    seen = set()
    for item in raw.replace("\n", ",").split(","):
        item = item.strip()
        if item and item not in seen:
            out.append(item)
            seen.add(item)
    return out


def parse_reasoning_efforts(raw: str | None) -> list[str]:
    raw = raw or "default"
    out = []
    seen = set()
    for item in raw.replace("\n", ",").split(","):
        item = item.strip()
        if item and item not in seen:
            out.append(item)
            seen.add(item)
    return out


def existing_view_paths(asset_db_dir: Path, rec: dict[str, Any]) -> list[Path]:
    rel_views = rec.get("indexing", {}).get("render_views") or []
    paths = [asset_db_dir / rel for rel in rel_views]
    paths = [p for p in paths if p.exists()]
    if paths:
        return paths
    asset_id = rec.get("identity", {}).get("asset_id")
    return sorted((asset_db_dir / "renders" / asset_id).glob("view_*.png"))


def vlm_prompt(rec: dict[str, Any], view_count: int) -> str:
    ident = rec.get("identity", {})
    geom = rec.get("geometry", {})
    dims = geom.get("dimensions_m", {})
    tech = rec.get("technical", {})
    return (
        "You are cataloging a single 3D asset for a general, multi-genre scene-generation asset database "
        "(scenes span many settings: modern city/street, industrial/logistics, suburban/residential, retail, "
        "rural/nature, harbor, medieval, fantasy/gothic, ancient temple, middle-eastern, east-asian, winter, sci-fi, indoor). "
        f"You are shown {view_count} rendered views of ONE object from different angles (orbit). "
        "Describe ONLY this object (ignore the gray ground plane and sky). "
        f"Measured size in meters (from the engine): width {dims.get('width')}, depth {dims.get('depth')}, height {dims.get('height')}. "
        f"Asset name hint: '{ident.get('name') or ident.get('asset_id')}'. "
        f"Source pack: '{ident.get('source_pack')}'. "
        f"Unreal asset path hint: '{tech.get('unreal_asset_path')}'. "
        "Fill every field. Pick the single best-fit category from the allowed enum. "
        "For 'setting': choose the single primary thematic setting/genre this asset most reads as, from the allowed enum "
        "(modern_urban, industrial, suburban_residential, commercial_retail, nature_rural, coastal_harbor, medieval, "
        "fantasy_gothic, ancient_temple, middle_eastern, east_asian, winter, sci_fi, indoor, generic). "
        "Use 'generic' ONLY for plain, style-neutral props that fit many settings equally."
    )


def run_vlm(
    *,
    rec: dict[str, Any],
    view_paths: list[Path],
    schema: Path,
    model: str,
    reasoning_effort: str,
    codex_bin: str,
    tmp_output: Path,
    timeout: int,
) -> tuple[dict[str, Any], dict[str, Any]]:
    tmp_output.parent.mkdir(parents=True, exist_ok=True)
    if tmp_output.exists():
        tmp_output.unlink()
    args = [
        codex_bin,
        "exec",
        "--json",
        "--skip-git-repo-check",
        "--dangerously-bypass-approvals-and-sandbox",
        "-m",
        model,
    ]
    if reasoning_effort != "default":
        args += ["-c", f'model_reasoning_effort="{reasoning_effort}"']
    args += [
        "--output-schema",
        str(schema),
        "-o",
        str(tmp_output),
        "-C",
        "/tmp",
    ]
    for path in view_paths:
        args += ["-i", str(path)]
    env = dict(os.environ, NO_COLOR="1")
    completed = subprocess.run(
        args,
        input=vlm_prompt(rec, len(view_paths)),
        text=True,
        env=env,
        timeout=timeout,
        capture_output=True,
        check=False,
    )
    trace = parse_codex_jsonl(completed.stdout)
    trace["returncode"] = completed.returncode
    trace["stderr_tail"] = completed.stderr[-4000:]
    if tmp_output.exists():
        return load_json(tmp_output), trace
    if trace.get("last_agent_text"):
        try:
            return json.loads(trace["last_agent_text"]), trace
        except json.JSONDecodeError:
            pass
    raise RuntimeError(
        "Codex VLM call failed or produced no output file "
        f"(returncode={completed.returncode}). stderr tail:\n{trace['stderr_tail']}"
    )


def parse_codex_jsonl(stdout: str) -> dict[str, Any]:
    trace: dict[str, Any] = {
        "thread_id": None,
        "usage": None,
        "last_agent_text": None,
        "raw_event_count": 0,
    }
    for line in stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        trace["raw_event_count"] += 1
        if event.get("type") == "thread.started":
            trace["thread_id"] = event.get("thread_id")
        elif event.get("type") == "turn.completed":
            trace["usage"] = event.get("usage")
        elif event.get("type") == "item.completed":
            item = event.get("item") or {}
            if item.get("type") == "agent_message":
                trace["last_agent_text"] = item.get("text")
    return trace


def assemble_record(old: dict[str, Any], vlm: dict[str, Any], model: str) -> dict[str, Any]:
    ident = old.get("identity", {})
    semantic = old.get("semantic", {})
    geometry = dict(old.get("geometry", {}))
    indexing = dict(old.get("indexing", {}))
    geometry["is_symmetric"] = vlm.get("is_symmetric")
    indexing["caption_model"] = model
    indexing["schema_version"] = indexing.get("schema_version") or "1.0"
    indexing["regenerated_from_asset_id"] = ident.get("asset_id")
    indexing["regenerated_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat()
    return {
        "identity": {
            "asset_id": ident.get("asset_id"),
            "name": vlm.get("display_name") or ident.get("name"),
            "category": vlm.get("category"),
            "subcategory": vlm.get("subcategory"),
            "source_pack": ident.get("source_pack"),
        },
        "semantic": {
            "short_description": vlm.get("short_description"),
            "description": vlm.get("description"),
            "tags": vlm.get("tags", []),
            "style": vlm.get("style"),
            "materials": vlm.get("materials", []),
            "color_palette": vlm.get("color_palette", []),
            "mood": vlm.get("mood", []),
            "typical_placement": vlm.get("typical_placement", []),
            "function": vlm.get("function"),
            "affordances": vlm.get("affordances", []),
            "scene_types": vlm.get("scene_types", []),
            "condition": vlm.get("condition"),
            "setting": vlm.get("setting"),
        },
        "geometry": geometry,
        "technical": old.get("technical", {}),
        "indexing": indexing,
    }


def markdown_report(model: str, comparisons: list[dict[str, Any]]) -> str:
    lines = [
        f"# VLM Metadata Regeneration Comparison: {model}",
        "",
        "Compared fields: " + ", ".join(VLM_FIELD_PATHS),
        "",
        "| asset_id | name | category | setting | tags J | materials J | changed fields |",
        "|---|---|---|---|---:|---:|---:|",
    ]
    for comp in comparisons:
        fields = comp["fields"]
        cat = fields["identity.category"]
        setting = fields["semantic.setting"]
        tags = fields["semantic.tags"]
        mats = fields["semantic.materials"]
        cat_text = f"{cat.get('old')} -> {cat.get('new')}" if cat["changed"] else str(cat.get("old"))
        setting_text = f"{setting.get('old')} -> {setting.get('new')}" if setting["changed"] else str(setting.get("old"))
        name_text = comp["baseline_name"]
        if comp["baseline_name"] != comp["new_name"]:
            name_text = f"{comp['baseline_name']} -> {comp['new_name']}"
        lines.append(
            "| {asset_id} | {name} | {cat} | {setting} | {tags_j} | {mats_j} | {changed} |".format(
                asset_id=comp["asset_id"],
                name=name_text,
                cat=cat_text,
                setting=setting_text,
                tags_j=tags.get("jaccard"),
                mats_j=mats.get("jaccard"),
                changed=comp["changed_field_count"],
            )
        )
    lines.extend(
        [
            "",
            "## Per-field Change Counts",
            "",
            "| field | changed assets |",
            "|---|---:|",
        ]
    )
    for field in VLM_FIELD_PATHS:
        count = sum(1 for c in comparisons if c["fields"][field]["changed"])
        lines.append(f"| {field} | {count} |")
    lines.append("")
    return "\n".join(lines)


def summarize_usage(usage_records: list[dict[str, Any]]) -> dict[str, Any]:
    keys = ["input_tokens", "cached_input_tokens", "output_tokens", "reasoning_output_tokens"]
    totals = {f"total_{key}": 0 for key in keys}
    usable = 0
    for rec in usage_records:
        usage = rec.get("usage") or {}
        if usage:
            usable += 1
        for key in keys:
            totals[f"total_{key}"] += int(usage.get(key) or 0)
    return {
        "usage_records": usable,
        **totals,
        "total_tokens": totals["total_input_tokens"] + totals["total_output_tokens"],
        "total_uncached_input_tokens": totals["total_input_tokens"] - totals["total_cached_input_tokens"],
        "avg_input_tokens": round(totals["total_input_tokens"] / usable, 1) if usable else 0,
        "avg_output_tokens": round(totals["total_output_tokens"] / usable, 1) if usable else 0,
    }


def summarize_model(
    comparisons: list[dict[str, Any]],
    usage_records: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    n = len(comparisons) or 1
    list_fields = [
        "semantic.tags",
        "semantic.materials",
        "semantic.color_palette",
        "semantic.mood",
        "semantic.typical_placement",
        "semantic.affordances",
        "semantic.scene_types",
    ]
    summary = {
        "assets_compared": len(comparisons),
        "category_agreement": round(
            sum(not field_changed(c, "identity.category") for c in comparisons) / n,
            3,
        ),
        "setting_agreement": round(
            sum(not field_changed(c, "semantic.setting") for c in comparisons) / n,
            3,
        ),
        "symmetry_agreement": round(
            sum(not field_changed(c, "geometry.is_symmetric") for c in comparisons) / n,
            3,
        ),
        "avg_changed_field_count": round(
            sum(c["changed_field_count"] for c in comparisons) / n,
            2,
        ),
    }
    for field in list_fields:
        key = "mean_" + field.split(".")[-1] + "_jaccard"
        summary[key] = round(sum(list_jaccard(c, field) for c in comparisons) / n, 3)
    summary["critical_changes"] = [
        {
            "asset_id": c["asset_id"],
            "category_changed": field_changed(c, "identity.category"),
            "setting_changed": field_changed(c, "semantic.setting"),
            "tags_jaccard": list_jaccard(c, "semantic.tags"),
            "materials_jaccard": list_jaccard(c, "semantic.materials"),
        }
        for c in comparisons
        if field_changed(c, "identity.category")
        or field_changed(c, "semantic.setting")
        or list_jaccard(c, "semantic.tags") < 0.35
        or list_jaccard(c, "semantic.materials") < 0.35
    ]
    summary["usage"] = summarize_usage(usage_records or [])
    return summary


def combined_report(
    *,
    asset_ids: list[str],
    model_results: dict[str, list[dict[str, Any]]],
    summaries: dict[str, dict[str, Any]],
) -> str:
    lines = [
        "# Lighter Model Metadata Benchmark",
        "",
        "Baseline is the existing catalog generated with `gpt-5.5`. The benchmark regenerates the VLM-derived fields from the stored render images and compares them against that baseline.",
        "",
        "`default` means no reasoning override was passed to Codex; it inherits the user's Codex config. `low` is the lowest reasoning effort exposed by this Codex model cache.",
        "",
        "Important: agreement with `gpt-5.5` is a proxy for compatibility, not absolute truth. Rows with category/setting changes or low tag/material overlap need manual inspection.",
        "",
        f"Assets sampled: {len(asset_ids)}",
        "",
        "## Model Summary",
        "",
        "| model | category agree | setting agree | tags J | materials J | avg changed fields | input tok | cached tok | output tok | reasoning tok | critical rows |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for model, summary in summaries.items():
        usage = summary.get("usage") or {}
        lines.append(
            "| {model} | {cat} | {setting} | {tags} | {mats} | {changed} | {input_tok} | {cached_tok} | {output_tok} | {reasoning_tok} | {critical} |".format(
                model=model,
                cat=summary["category_agreement"],
                setting=summary["setting_agreement"],
                tags=summary["mean_tags_jaccard"],
                mats=summary["mean_materials_jaccard"],
                changed=summary["avg_changed_field_count"],
                input_tok=usage.get("total_input_tokens", 0),
                cached_tok=usage.get("total_cached_input_tokens", 0),
                output_tok=usage.get("total_output_tokens", 0),
                reasoning_tok=usage.get("total_reasoning_output_tokens", 0),
                critical=len(summary["critical_changes"]),
            )
        )

    lines.extend(
        [
            "",
            "## Sampled Assets",
            "",
            "| asset_id |",
            "|---|",
        ]
    )
    for asset_id in asset_ids:
        lines.append(f"| {asset_id} |")

    for model, comparisons in model_results.items():
        lines.extend(
            [
                "",
                f"## {model} Per-Asset",
                "",
                "| asset_id | category | setting | tags J | materials J | changed fields |",
                "|---|---|---|---:|---:|---:|",
            ]
        )
        for comp in comparisons:
            fields = comp["fields"]
            cat = fields["identity.category"]
            setting = fields["semantic.setting"]
            cat_text = f"{cat.get('old')} -> {cat.get('new')}" if cat["changed"] else str(cat.get("old"))
            setting_text = f"{setting.get('old')} -> {setting.get('new')}" if setting["changed"] else str(setting.get("old"))
            lines.append(
                "| {asset_id} | {cat} | {setting} | {tags} | {mats} | {changed} |".format(
                    asset_id=comp["asset_id"],
                    cat=cat_text,
                    setting=setting_text,
                    tags=fields["semantic.tags"].get("jaccard"),
                    mats=fields["semantic.materials"].get("jaccard"),
                    changed=comp["changed_field_count"],
                )
            )

        critical = summaries[model]["critical_changes"]
        lines.extend(["", f"### {model} Critical Rows", ""])
        if not critical:
            lines.append("No category/setting changes or low-overlap rows.")
        else:
            lines.extend(
                [
                    "| asset_id | category changed | setting changed | tags J | materials J |",
                    "|---|---:|---:|---:|---:|",
                ]
            )
            for row in critical:
                lines.append(
                    "| {asset_id} | {cat} | {setting} | {tags} | {mats} |".format(
                        asset_id=row["asset_id"],
                        cat=row["category_changed"],
                        setting=row["setting_changed"],
                        tags=row["tags_jaccard"],
                        mats=row["materials_jaccard"],
                    )
                )
        lines.extend(
            [
                "",
                f"### {model} Output Snapshots",
                "",
                "| asset_id | generated name | category | setting | short description | tags |",
                "|---|---|---|---|---|---|",
            ]
        )
        for comp in comparisons:
            snap = comp.get("new_snapshot") or {}
            tags = ", ".join(str(x) for x in snap.get("tags", []))
            short_desc = str(snap.get("short_description") or "").replace("|", "\\|")
            lines.append(
                "| {asset_id} | {name} | {cat} | {setting} | {desc} | {tags} |".format(
                    asset_id=comp["asset_id"],
                    name=str(snap.get("name") or "").replace("|", "\\|"),
                    cat=str(snap.get("category") or "").replace("|", "\\|"),
                    setting=str(snap.get("setting") or "").replace("|", "\\|"),
                    desc=short_desc,
                    tags=tags.replace("|", "\\|"),
                )
            )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--asset-db-dir", default=os.environ.get("ASSET_DB_DIR", "/data/siddhant/asset_db"))
    parser.add_argument("--asset-ids", help="Comma-separated asset IDs to regenerate.")
    parser.add_argument("--asset-id-file", help="Text file with one asset ID per line.")
    parser.add_argument("--manifest", help="Manifest JSON to select asset IDs from.")
    parser.add_argument("--limit", type=int, default=20)
    parser.add_argument("--output-dir", help="Output directory. Default: $ASSET_DB_DIR/metadata_compare/<timestamp>.")
    parser.add_argument("--schema", default=str(Path(__file__).with_name("vlm_output_schema.json")))
    parser.add_argument("--model", default=os.environ.get("CODEX_MODEL", "gpt-5.5"))
    parser.add_argument("--models", help="Comma-separated Codex models. Overrides --model.")
    parser.add_argument("--reasoning-efforts", default="default", help="Comma-separated efforts: default, low, medium, high, xhigh.")
    parser.add_argument("--codex-bin", default=os.environ.get("CODEX_BIN", "codex"))
    parser.add_argument("--timeout", type=int, default=300)
    parser.add_argument("--dry-run", action="store_true", help="Write selected_assets.json only; do not call the model.")
    parser.add_argument("--force", action="store_true", help="Regenerate even when benchmark JSONs already exist.")
    args = parser.parse_args()

    asset_db_dir = Path(args.asset_db_dir)
    records = find_catalog_records(asset_db_dir)
    if not records:
        print(f"ERROR: no catalog records found under {asset_db_dir}/catalog", file=sys.stderr)
        return 1

    asset_ids = parse_asset_ids(args.asset_ids, args.asset_id_file)
    if not asset_ids and args.manifest:
        asset_ids = select_from_manifest(Path(args.manifest), args.limit)
    if not asset_ids:
        asset_ids = select_balanced(records, args.limit)
    asset_ids = asset_ids[: args.limit]

    missing = [asset_id for asset_id in asset_ids if asset_id not in records]
    if missing:
        print("ERROR: selected asset IDs missing from current catalog:", ", ".join(missing), file=sys.stderr)
        return 1

    timestamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d_%H%M%S")
    out_dir = Path(args.output_dir) if args.output_dir else asset_db_dir / "metadata_compare" / timestamp
    out_dir.mkdir(parents=True, exist_ok=True)

    selected = {
        "asset_db_dir": str(asset_db_dir),
        "models": parse_models(args.model, args.models),
        "reasoning_efforts": parse_reasoning_efforts(args.reasoning_efforts),
        "schema": str(Path(args.schema)),
        "asset_ids": asset_ids,
    }
    write_json(out_dir / "selected_assets.json", selected)
    print(f"selected {len(asset_ids)} assets -> {out_dir / 'selected_assets.json'}")
    if args.dry_run:
        return 0

    model_results: dict[str, list[dict[str, Any]]] = {}
    summaries: dict[str, dict[str, Any]] = {}
    all_usage: dict[str, list[dict[str, Any]]] = {}
    for model in parse_models(args.model, args.models):
      for reasoning_effort in parse_reasoning_efforts(args.reasoning_efforts):
        variant_label = f"{model}/{reasoning_effort}"
        model_dir = out_dir / "models" / safe_variant_name(model, reasoning_effort)
        regenerated_dir = model_dir / "regenerated"
        usage_dir = model_dir / "usage"
        comparisons: list[dict[str, Any]] = []
        usage_records: list[dict[str, Any]] = []
        for idx, asset_id in enumerate(asset_ids, start=1):
            old = load_json(records[asset_id])
            views = existing_view_paths(asset_db_dir, old)
            if len(views) < 1:
                raise RuntimeError(f"{asset_id}: no render views found")
            out_json = regenerated_dir / f"{asset_id}.json"
            usage_json = usage_dir / f"{asset_id}.json"
            if out_json.exists() and not args.force:
                new = load_json(out_json)
                print(f"[{variant_label} {idx}/{len(asset_ids)}] reuse {asset_id}", flush=True)
                usage_rec = load_json(usage_json) if usage_json.exists() else {
                    "asset_id": asset_id,
                    "model": model,
                    "reasoning_effort": reasoning_effort,
                    "usage": None,
                }
            else:
                print(f"[{variant_label} {idx}/{len(asset_ids)}] regenerating {asset_id} from {len(views)} views", flush=True)
                tmp_output = model_dir / "_tmp_vlm_out.json"
                vlm, trace = run_vlm(
                    rec=old,
                    view_paths=views,
                    schema=Path(args.schema),
                    model=model,
                    reasoning_effort=reasoning_effort,
                    codex_bin=args.codex_bin,
                    tmp_output=tmp_output,
                    timeout=args.timeout,
                )
                new = assemble_record(old, vlm, model)
                write_json(out_json, new)
                usage_rec = {
                    "asset_id": asset_id,
                    "model": model,
                    "reasoning_effort": reasoning_effort,
                    "thread_id": trace.get("thread_id"),
                    "usage": trace.get("usage"),
                    "returncode": trace.get("returncode"),
                    "raw_event_count": trace.get("raw_event_count"),
                }
                write_json(usage_json, usage_rec)
                usage = usage_rec.get("usage") or {}
                print(
                    "[{variant} {idx}/{total}] usage input={input} cached={cached} output={output} reasoning={reasoning}".format(
                        variant=variant_label,
                        idx=idx,
                        total=len(asset_ids),
                        input=usage.get("input_tokens"),
                        cached=usage.get("cached_input_tokens"),
                        output=usage.get("output_tokens"),
                        reasoning=usage.get("reasoning_output_tokens"),
                    ),
                    flush=True,
                )
            comparisons.append(compare_records(old, new))
            usage_records.append(usage_rec)
            write_json(model_dir / "comparison.json", comparisons)
            (model_dir / "comparison.md").write_text(markdown_report(variant_label, comparisons), encoding="utf-8")
            summaries[variant_label] = summarize_model(comparisons, usage_records)
            model_results[variant_label] = comparisons
            all_usage[variant_label] = usage_records
            write_json(out_dir / "summary.json", summaries)
            write_json(out_dir / "usage.json", all_usage)
            (out_dir / "report.md").write_text(
                combined_report(asset_ids=asset_ids, model_results=model_results, summaries=summaries),
                encoding="utf-8",
            )
        tmp_output = model_dir / "_tmp_vlm_out.json"
        if tmp_output.exists():
            tmp_output.unlink()
    print(f"wrote model outputs under {out_dir / 'models'}")
    print(f"wrote combined report to {out_dir / 'report.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
